title: CCF-TCARCH--HLS算法挑战赛
description:  CCF-TCARCH--HLS算法挑战赛
show_downloads: true
google_analytics: UA-190340802-1
theme: jekyll-theme-dinky
include: [ 'contributing.md']
baseurl: '/ccf-tcarch--hls'
